export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const ADD_PEOPLE_SUCCESS = 'ADD_PEOPLE_SUCCESS';
export const UPDATE_PEOPLE_SUCCESS = 'UPDATE_PEOPLE_SUCCESS';
export const REPORT_INFECTED_PEOPLE_SUCCESS = 'REPORT_INFECTED_PEOPLE_SUCCESS';